/*

 codeNodes v0.0.1

 Copyright (c) 2013 Sebastian Boethin <boethin@codenodes.org>
 codeNodes is open sourced under the MIT license
 Report bugs to: bugs@codenodes.org
 See also: http://codenodes.org
*/
(function(){function r(){this.g=this.m=this.a=null}function n(){this.a=null}function t(){this.pattern=this.a=null}function v(h,a){this.lang=h;this.name=a}function q(h){if(!p.j(h))throw Error("Argument 'lang' cannot be empty.");this.lang=h;this.e={}}function l(){this.a=null}function s(){var h=this.c=[];p.d(this,"nodes",function(){return h});p.d(this,"length",function(){return h.length})}RegExp.prototype.u=function(){for(var h=0,a=this.source,b=0,c=a.length;b<c;++b)switch(a[b]){case "\\":++b;break;
case "(":"?"===a[b+1]&&":"===a[b+2]||++h}return h};var p={j:function(h){return"string"===typeof h&&0<h.length},H:function(h){return h.replace(/([\.\\\+\*\?\[\^\]\$\(\)])/g,"\\$1")},d:function(h,a,b){Object.defineProperty(h,a,{get:b})}};s.prototype.toString=function(h){return this.c.map(function(a){return f.o(a,h)}).join("")};s.prototype.push=function(h,a){if("string"==typeof h)h.length&&(this.c.length&&"string"==typeof this.c[this.c.length-1]?(this.c[this.c.length-1]+=h,a("TextNodeAppended",h)):(this.c.push(h),
a("TextNodeCreating",h)));else if(h instanceof f)this.c.push(h),a("NodeCreating",h);else throw Error("Argument 'node' must be either a string or a Node instance.");};s.prototype.toString=s.prototype.toString;var f=function a(b,c,m){if(!b)throw Error("Argument 'rule' cannot be null.");var e={yield:function(a){if("function"!=typeof a)throw Error("Property 'yield' must be a function.");return function(b){a(m,b)}}},k;for(k in b.a)this[k]=e[k]?e[k](b.a[k]):b.a[k];p.d(this,"scope",function(){return c});
p.d(this,"match",function(){return m});var g=null;p.d(this,"result",function(){g||(g=new (a.I()));return g});p.d(this,"length",function(){return g?g.length:0})};f.prototype.toString=function(a){a=a||f.h;return f.o(this,a)};f.h=function(a,b){var c;return"string"==typeof a?a:p.j(c=a["class"])?"<"+c+">"+b+"</"+c+">":b};f.o=function(a,b){b=b||f.h;if("string"==typeof a)return b(a);if(!(a instanceof f))throw Error("Argument 'node' must be either a string or an instance of Node.");var c=a.length?a.result.toString(b):
a.match[0];return b(a,c)};f.I=function(){return s};f.prototype.toString=f.prototype.toString;f.defaultStringify=f.h;l.prototype.b=function(a){a=a||{};a.hasOwnProperty("scope")||(a.scope={main:0});this.a=a;return this};l.prototype.r=function(a){return this.a.scope[a]};l.prototype.A=function(a){for(var b in this.a.scope)a(b)};l.prototype.l=function(a){if(!this.q){var b=this.f();this.q=[b,b.u()]}a.apply(null,this.q)};l.prototype.f=function(){throw Error("Abstract function call.");};l.prototype.handle=
function(a,b,c,m,e){if("function"==typeof this.a.handler)this.a.handler.call(this,a,b,g,c,m,e);else{var k=b.substr(0,m);b=b.substr(c[0].length+m);var g;(g=this.a.lookBehind)&&!k.match(g)&&console.log("lookBehind failed: '"+k+"'");e(k,b,new f(this,a,c))}};l.prototype.init=l.prototype.b;q.prototype.b=function(a){if(!(a instanceof Array&&0<a.length))throw Error("Argument 'rules' must be a non-empty array.");var b={};(function(b){for(var e in a)b(a[e])})(function(a){a.A(function(e){b[e]||(b[e]=[]);b[e].push(a)})});
this.s={};for(var c in b)this.s[c]=(new v(this.lang,c)).b(b[c]);return this};q.prototype.addEventListener=function(a,b){this.e[a]||(this.e[a]=[]);this.e[a].push(b)};q.prototype.K=function(a,b){if(this.e[a])for(var c in this.e[a])this.e[a][c].apply(this,b)};q.prototype.p=function(a,b,c,m,e,k,g){e=e||"";k=k||"";g=g||0;var d=this.s[a];if(!d)throw Error("Scope '"+a+"' doesn't exist.");(function(a){function f(b,e){a.K(b,[a.lang,d,e,g])}c.push(e,f);(function(a){a(a,b)})(function(b,e){d.B(e,function(e,d,
l){function n(){p.j(d)?b(b,d):(c.push(k,f),f("NodeCreated",c),m(c))}c.push(e,f);l?(c.push(l,f),"function"==typeof l.yield?l.yield(function(b,e,m,c,k){a.p(e,m,l.result,n,c,k,g+1)}):n()):n()})})})(this)};q.prototype.addEventListener=q.prototype.addEventListener;v.prototype.b=function(a){(function(b){a.sort(function(a,m){return m.r(b)-a.r(b)})})(this.name);this.i=[];this.rules=[];this.l=function(b,c){(function(b){for(var e in a)b(this,a[e],++c)}).call(this,function(a,e,k){e.l(function(g,d){b.push(g.source);
a.i.push(k);a.rules.push(function(b,c){c(a,b.slice(k,d+k+1),b.index,e)});c+=d})});return RegExp(b.map(function(a){return"("+a+")"}).join("|"))}.call(this,[],0);return this};v.prototype.B=function(a,b){var c;if(null!=(c=a.match(this.l)))for(var m in this.i)if("undefined"!=typeof c[this.i[m]]){this.rules[m].call(this,c,function(e,c,m,d){d.handle(e,a,c,m,b)});return}b(a)};t.prototype=new l;t.prototype.b=function(a){this.constructor.prototype.b.call(this,a);if(!this.a.hasOwnProperty("pattern"))throw Error("Missing property: 'pattern'.");
return this};t.prototype.f=function(){return RegExp(this.a.pattern)};t.prototype.init=t.prototype.b;n.prototype=new l;n.prototype.b=function(a){this.constructor.prototype.b.call(this,a);if(!this.a.hasOwnProperty("words"))throw Error("Missing property: 'words'.");this.a.hasOwnProperty("before")||(this.a.before="\\b");this.a.hasOwnProperty("after")||(this.a.after="\\b");return this};n.prototype.f=function(){var a=n.D(this.a.words);return RegExp(this.a.before+a+this.a.after)};n.D=function(a){function b(a,
e,c){a=a.replace(/([\.\\\+\*\?\[\^\]\$\(\)])/g,"\\$1");e.length&&(a+="(?:"+e.map(function(a){return b.apply(null,a)}).join("|")+")",c&&(a+="?"));return a}function c(a,b,d){if(!(1<b.length))return[a,b,d];var g=b[0][0][0];if(g!==b[1][0][0]){if(!(2<b.length))return[a,b,d];g=b.shift();b=c("",b,!1);if(0<b[0].length)return[a,[g,b],d];b[1].unshift(g);return[a,b[1],d]}for(var f=[],l=!1;b.length;){if(b[0][0][0]==g)b[0][0]=b[0][0].substr(1);else break;var n=b.shift();n[0].length?f.push(n):l=!0}if(b.length||
d){g=c(g,f,l);if(b.length){b=c("",b,!1);if(b[0].length)return[a,[g,b],d];b[1].unshift(g);return[a,b[1],d]}b.unshift(g);return[a,b,d]}return c(a+g,f,l)}a.sort();a=a.map(function(a){return[a,[],!1]});return b.apply(null,c("",a,!1))};n.prototype.init=n.prototype.b;r.prototype=new l;r.prototype.b=function(a){l.prototype.b.call(this,a);this.m=this.a.begin||"/*";this.g=this.a.end||"*/";return this};r.prototype.f=function(){return RegExp(p.H(this.m))};r.prototype.handle=function(a,b,c,d,e){c=b.substr(0,
d);var k,g;0<(g=b.indexOf(this.g,d+this.m.length))?(k=b.substr(g+this.g.length),b=b.substr(d,g-d+this.g.length)):(k="",b=b.substr(d));e(c,k,new f(this,a,[b]))};r.prototype.init=r.prototype.b;var u={};u.Result=s;u.Node=f;u.Language=q;u.Scope=v;u.RuleBase=l;var w={};w.PatternRule=t;w.KeywordRule=n;w.BlockCommentRule=r;var d={k:{},F:["XML","test"],w:function(a,b){d.C(a,function(a,d){if(a)return b(a);b(null,d,function(a,b){d.p("main",a,new s,function(a){b(a)})})},d.G)},v:function(a,b){return(new q(a)).b(b())},
t:function(a){a(null,d.F)},J:function(a,b){return d.k[a]=b},C:function(a,b,c){var f;(f=d.k[a])?b(null,f):c(a,b)},G:function(a,b){if("function"!=typeof d.langScriptUri)return b("function required: codeNodes.langScriptUri");var c=d.langScriptUri(a);d.n(c);(function(a,b){a(a,b)})(function(f,e){setTimeout(function(){console.log("wait("+e+")");"object"==typeof(rules=d.k[a])?b(null,rules):100>e?f(f,e+1):b("timeout while loading '"+c+"'")},100)},0)},b:function(a){d.langScriptUri=a},n:function(a){var b=document.createElement("script");
b.setAttribute("src",a);b.setAttribute("type","text/javascript");document.body.appendChild(b)}};d.createProcessor=d.w;d.compileLanguage=d.v;d.availableLanguages=d.t;d.setRules=d.J;d.init=d.b;d.appendScript=d.n;d.Core=u;d.Rules=w;window.codeNodes=d})();
